### ISSUE TITLE
Could not find module ‘Sound.Tidal.Context’   (vscode + stack)

### ISSUE THREAD

**Issue by janaipakos** [kindohm/vscode-tidalcycles#6]
Hi, thanks for making this. It seems like the repl is not importing tidal: `Could not find module ‘Sound.Tidal.Context’`

I'm successfully getting sound through SuperCollider, `shift+enter` highlights commands (d1 $ sound "bd sn"), and the tidalcycles repl is showing activity.

I use stack and set the path within vscode settings, and tried a boot file: 
```
"tidalcycles": {
        "ghciPath": "/Users/home/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghci",
        "tidalBootPath": "~/path/to/tidalcyclesBoot.hs"
        }
```

I also tried putting `import Sound.Tidal.Context` at the top of the test file, and calling it with `shift+enter` with not luck.

Any clue why Sound.Tidal.Context isn't being imported?

**Comment by kindohm** [comment]
@janaipakos thanks for the info. Usually that error means that Tidal is not installed (e.g. `cabal install tidal`). 

I'm confused about this:

> I'm successfully getting sound through SuperCollider, shift+enter highlights commands (d1 $ sound "bd sn"), and the tidalcycles repl is showing activity.

So when you eval a Tidal pattern in the VS Code editor with `shift+enter`, SuperCollider plays the samples and plays your pattern? But you still see the error?

**Comment by janaipakos** [comment]
SuperCollider plays sound, but VS Code does not. When I eval a Tidal patten in VS Code editor, the snipped it 'highlighted' but there's no sound produced for the sample.

I ended up running an instance of VS Code through `stack exec` and it worked :man_shrugging:

This is probably a stack quirk and not related to the plugin.

**Comment by kindohm** [comment]
ahh, got it. can we close this issue?

**Comment by janaipakos** [comment]
Yup, thanks :)

**Comment by pizzatero** [comment]
hi brothers, i have this problem in atom 
when I open the packages Tidal, I see this text:

Choose ghcup default path: /Users/miguelchaparro/.ghcup/bin
Ghci command: /Users/miguelchaparro/.ghcup/bin/ghci
Ghc-pkg command: /Users/miguelchaparro/.ghcup/bin/ghc-pkg
Load BootTidal.hs from /Users/miguelchaparro/.atom/packages/tidalcycles/lib/BootTidal.hs
t>


: error:
    Could not find module ‘Sound.Tidal.Context’
    It is not a module in the current program, or in any known package.

How can i do good?

best regards!

**Comment by kindohm** [comment]
`Could not find module 'Sound.Tidal.Context'` usually means that you do not have Tidal installed.

**Comment by pizzatero** [comment]
yeah bro!! I did it ! just i needed to put a code in terminal !
:)

*Miguel Chaparro *
+49 15143418810 / Germany
+57 3137322792 / Colombia
